# Generated by Django 4.0.3 on 2022-05-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolist_do_date_alter_todolist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
